apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-pact-broker-prod-data
  namespace: pact-broker
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
